//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TIDIP_ADO_NET_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Police
    {
        public int PoliceID { get; set; }
        [Required(ErrorMessage = "名稱為必填欄位")]
        public string PoliceName { get; set; }
        [Required(ErrorMessage = "請選擇縣市地區")]
        [StringLength(4, ErrorMessage = "請選擇縣市地區")]
        public string County_City { get; set; }
        [Required(ErrorMessage = "請選擇縣市地區")]
        [StringLength(4, ErrorMessage = "請選擇縣市地區")]
        public string Area { get; set; }
        [Required(ErrorMessage = "地址為必填欄位")]
        public string PoliceAddress { get; set; }

        public System.DateTime PoliceCreatedDate { get; set; }


        [Required(ErrorMessage = "地址為必填欄位")]
        public string PoliceTel { get; set; }
    }
}
